---
apiVersion: v1
kind: Service
metadata:
  name: blogdb
  labels:
    app: blogdb
spec:
  selector:
    app: blogdb
  ports:
  - name: blogdbport
    protocol: TCP
    targetPort: 3306
    port: 3306
